# Generated by Django 4.2.5 on 2023-09-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_portfolio_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('subject', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('massage', models.TextField()),
                ('is_read_by_admin', models.BooleanField(default=False)),
            ],
        ),
    ]
