# Generated by Django 4.2.5 on 2023-09-20 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contact_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email_url',
            field=models.CharField(default='mailto:80mahde@gmail.com', max_length=50),
        ),
        migrations.AddField(
            model_name='person',
            name='github_url',
            field=models.CharField(default='https://github.com/Mahdifm1', max_length=50),
        ),
        migrations.AddField(
            model_name='person',
            name='linkedin_url',
            field=models.CharField(default='https://www.linkedin.com/in/mahdi-lotfian/', max_length=50),
        ),
        migrations.AddField(
            model_name='person',
            name='telegram_url',
            field=models.CharField(default='https://t.me/Mahdi_lff', max_length=50),
        ),
    ]
