# Generated by Django 4.2.5 on 2023-09-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_person_email_url_person_github_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email_url',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='github_url',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='linkedin_url',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='telegram_url',
            field=models.CharField(max_length=50),
        ),
    ]
