# Generated by Django 4.2.5 on 2023-09-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_person_email_url_alter_person_github_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_experience',
            name='company_name',
            field=models.CharField(max_length=50),
        ),
    ]
